export const MATCH_SEARCH_ARRAY = 'MATCH_SEARCH_ARRAY';
export const GET_COINS = 'GET_COINS';
export const SELECT_COIN = 'SELECT_COIN';
export const GET_COIN_EXCHANGES_AND_TRADING_PAIRS = 'GET_COIN_EXCHANGES_AND_TRADING_PAIRS';
export const GET_TRADING_PAIRS_PRICE_HASH = 'GET_TRADING_PAIRS_PRICE_HASH';
export const GET_HOLDINGS = 'GET_HOLDINGS';
export const GET_COIN_USD_PRICE = 'GET_COIN_USD_PRICE';